import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Toaster } from "sonner";

const montserrat = Montserrat({
	weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} antialiased`}
				suppressHydrationWarning
			>
				<Toaster />
				<UserProvider>
					<AppRouterCacheProvider options={{ key: "css" }}>
						<ThemeProvider theme={theme}>{children}</ThemeProvider>
					</AppRouterCacheProvider>
				</UserProvider>
			</body>
		</html>
	);
}
